Make up the test of other bits
XuJiandong/rvv-testcases pull request #15
Opened 2022-06-13 09:27 UTC by joii2020

Make up the test of 8 16 32 128 512 1024 bits.
Optimization parameters, the test range can be controlled by parameters.
Upload tools used in development.

2022-06-16 02:03 UTC, XuJiandong requested changes

2022-06-16 02:03 UTC, XuJiandong commented on cases/src/main.rs
>              set_simple(true);
Use "--full" to replace "--simple". By default, it's a simple cases. When "--full" is specified, it becomes full cases.

2022-06-16 02:03 UTC, XuJiandong commented on cases/src/main.rs
> +        } else if data.find("--seed=").is_some() {
Don't forget to update CI to enable seed.

2022-06-16 02:03 UTC, XuJiandong commented on cases/src/rng_data.rs
> +pub static G_DATA: [u8; 512] = [
why is these data used?

2022-06-16 02:04 UTC, XuJiandong requested changes

2022-06-16 02:04 UTC, XuJiandong commented on cases/src/rng.rs
> +pub fn set_seed(seed: usize) {
Don't remove BestNumberRng. When seed is not provided, use these numbers.

2022-06-16 08:55 UTC, XuJiandong requested changes

2022-06-16 08:55 UTC, XuJiandong commented on cases/src/rng.rs
> +pub fn fill_rand_bytes(dest: &mut [u8]) {
Such code is not necessary if rng trait is implemented.

2022-06-16 09:03 UTC, XuJiandong requested changes

2022-06-16 09:03 UTC, XuJiandong commented on cases/src/rng_data.rs
> +pub static G_DATA: [u8; 512] = [
With PRNG, I think it's not needed.

2022-06-17 09:18 UTC, XuJiandong requested changes

2022-06-17 09:18 UTC, XuJiandong commented on cases/.vscode/launch.json
> +{
Remove this.

2022-06-17 09:18 UTC, XuJiandong commented on cases/src/main.rs
> +        } else if data.find("--fill").is_some() {
typo: full

2022-06-17 09:19 UTC, joii2020 commented on cases/src/main.rs
> +        } else if data.find("--fill").is_some() {
Sorry, correct it immediately

2022-06-20 02:30 UTC, XuJiandong approved these changes

2022-06-23 01:34 UTC, merged